version: '3.8'
services:
	service-1:
	build: ./service-1
	ports:
	-target: 5000
	published: 5000
	environment:
	-DATABASE_URI=mysql+pymysql://root:qaconsulting@34.89.80.142/flaskapp
	-SECRET_KEY='SDJSDJSKDKSSLD12'

	service-2:
        build: ./service-2
        ports:
        -target: 5000
        published: 5002
        environment:
        -DATABASE_URI=mysql+pymysql://root:qaconsulting@34.89.80.142/flaskapp
        -SECRET_KEY='SDJSDJSKDKSSLD12'

	service-3:
        build: ./service-3
        ports:
        -target: 5000
        published: 5003
        environment:
        -DATABASE_URI=mysql+pymysql://root:qaconsulting@34.89.80.142/flaskapp
        -SECRET_KEY='SDJSDJSKDKSSLD12'

	service-4:
        build: ./service-4
        ports:
        -target: 5000
        published: 5000
        environment:
        -DATABASE_URI=mysql+pymysql://root:qaconsulting@34.89.80.142/flaskapp
        -SECRET_KEY='SDJSDJSKDKSSLD12'
